# Auto-label PRs based on changed files

# Application areas
frontend:
  - changed-files:
    - any-glob-to-any-file: 'code/frontend/**/*'

backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'code/backend/**/*'
      # Exclude test files (they get their own label)
      - '!code/backend/**/*.Tests/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'code/backend/**/*.Tests/**/*'
      - '**/*[Tt]est*.cs'
      - '**/*[Ss]pec*.cs'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '*.md'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'

# Infrastructure
workflows:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - 'docker-compose*.yml'
      - '.dockerignore'

# Dependencies and configuration
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/*.csproj'
      - '**/packages.lock.json'
      - '**/yarn.lock'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*appsettings*.json'
      - '**/*.config'
      - '**/.env*'
      - '**/tsconfig*.json'
      - '**/angular.json'

chore:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '.gitignore'
      - '.editorconfig'
      - '.prettierrc*'
      - '.eslintrc*'
