name: Help request
description: Ask a question to receive help.
title: "[HELP] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        If you are experiencing unexpected behavior, please consider submitting a bug report instead.
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate check"
      options:
        - label: I have searched for existing issues and confirmed this is not a duplicate.
          required: true
  - type: checkboxes
    id: init
    attributes:
      label: "Before submitting a help request, I have:"
      options:
        - label: Reviewed the documentation.
          required: true
        - label: Ensured I am using ghcr.io/cleanuparr/testing docker repository.
          required: true
        - label: Ensured I am using the latest version.
          required: true
        - label: Enabled verbose logging.
          required: true
  - type: textarea
    id: description
    attributes:
      label: How can we help?
      description: |
        Links? References? Anything that will give us more context about your question!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true